/* exportFont.js — gera arquivo OTF a partir de contornos por glyph.
   Tabela `name` montada manualmente para passar na validação do macOS. */
(function (global) {
  const TG = global.TG;

  function sanitizeForName(s) {
    if (!s) return 'Regular';
    return String(s)
      .normalize('NFKD').replace(/[̀-ͯ]/g, '')
      .replace(/°/g, ' deg')
      .replace(/[<>\(\)\[\]\{\}\/%]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim() || 'Regular';
  }

  function sanitizeForPS(s) {
    if (!s) return 'Regular';
    const ascii = String(s)
      .normalize('NFKD').replace(/[̀-ͯ]/g, '')
      .replace(/°/g, 'Deg')
      .replace(/%/g, 'Pct')
      .replace(/&/g, 'And')
      .replace(/[^A-Za-z0-9_-]/g, '');
    return (ascii || 'Regular').slice(0, 63);
  }

  function contoursToOTPath(contours) {
    const path = new opentype.Path();
    for (const c of contours) {
      if (!c || c.length < 3) continue;
      path.moveTo(c[0][0], c[0][1]);
      for (let i = 1; i < c.length; i++) path.lineTo(c[i][0], c[i][1]);
      path.close();
    }
    return path;
  }

  function glyphName(ch) { return (TG.agl && TG.agl.forName) ? TG.agl.forName(ch) : ch; }

  function buildFont(processGlyphFn, opts = {}) {
    const src = TG.fontSource;
    const m = src ? src.metrics() : { unitsPerEm: 1000, ascender: 800, descender: -200 };
    const defaultAW = src ? src.defaultAdvance() : 600;

    const notdefPath = new opentype.Path();
    notdefPath.moveTo(100, 0); notdefPath.lineTo(100, m.ascender * 0.875);
    notdefPath.lineTo(m.unitsPerEm * 0.5, m.ascender * 0.875);
    notdefPath.lineTo(m.unitsPerEm * 0.5, 0); notdefPath.close();
    const notdef = new opentype.Glyph({
      name: '.notdef', unicode: 0, advanceWidth: defaultAW, path: notdefPath,
    });

    const glyphs = [notdef];
    const seen = new Set();
    const chars = src ? src.listChars() : TG.alphabet.listChars();
    for (const ch of chars) {
      if (seen.has(ch)) continue;
      seen.add(ch);
      const source = src ? src.getSource(ch) : { kind: 'skeleton', prims: TG.alphabet.get(ch), advanceWidth: defaultAW };
      const contours = processGlyphFn(ch, source) || [];
      const path = contoursToOTPath(contours);
      glyphs.push(new opentype.Glyph({
        name: glyphName(ch),
        unicode: ch.codePointAt(0),
        advanceWidth: source.advanceWidth || defaultAW,
        path,
      }));
    }

    const familyHuman = sanitizeForName(opts.familyName || 'TypeGen');
    const styleHuman  = sanitizeForName(opts.styleName  || 'Regular');
    const psFamily    = sanitizeForPS(familyHuman);
    const psStyle     = sanitizeForPS(styleHuman);
    const fullName    = `${familyHuman} ${styleHuman}`;
    const psName      = `${psFamily}-${psStyle}`.slice(0, 63);
    const version     = '1.000';
    const year        = new Date().getFullYear();

    const font = new opentype.Font({
      familyName:  familyHuman,
      styleName:   styleHuman,
      unitsPerEm:  m.unitsPerEm,
      ascender:    m.ascender,
      descender:   m.descender,
      glyphs,
      designer:        'TypeGen',
      designerURL:     'https://mscrofft.github.io/TypeGen',
      manufacturer:    'TypeGen',
      manufacturerURL: 'https://mscrofft.github.io/TypeGen',
      license:         'SIL Open Font License v1.1',
      licenseURL:      'https://scripts.sil.org/OFL',
      version,
      description:     'Generated by TypeGen',
      copyright:       `© ${year} TypeGen`,
    });

    // Sobrescreve a tabela name com registros explícitos (corrige avisos do macOS).
    font.names = font.names || {};
    const setName = (key, val) => { font.names[key] = { en: val }; };
    setName('fontFamily',     familyHuman);
    setName('fontSubfamily',  styleHuman);
    setName('fullName',       fullName);
    setName('postScriptName', psName);
    setName('uniqueID',       `TypeGen ${familyHuman} ${styleHuman} ${version}`);
    setName('version',        `Version ${version}`);
    setName('manufacturer',   'TypeGen');
    setName('designer',       'TypeGen');
    setName('description',    'Generated by TypeGen');
    setName('copyright',      `© ${year} TypeGen`);
    setName('license',        'SIL Open Font License v1.1');
    setName('licenseURL',     'https://scripts.sil.org/OFL');
    setName('manufacturerURL','https://mscrofft.github.io/TypeGen');
    setName('designerURL',    'https://mscrofft.github.io/TypeGen');

    return font;
  }

  function downloadFont(font, filename) {
    font.download(filename);
  }

  global.TG.exportFont = { buildFont, downloadFont, contoursToOTPath, sanitizeForName, sanitizeForPS };
})(window);
